# Generated by Django 5.1.1 on 2024-09-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('slug', models.SlugField(max_length=40, null=True, unique=True)),
            ],
        ),
    ]
