# Generated by Django 5.1.1 on 2024-11-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Adopter',
        ),
    ]
