# Generated by Django 5.1.1 on 2024-11-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_profile_adopter'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='adopted_dogs',
            field=models.ManyToManyField(related_name='adopters', to='app.dog'),
        ),
    ]
