# Generated by Django 5.1.1 on 2024-11-12 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_adopter_adopted_dogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopter',
            name='adopted_dogs',
        ),
        migrations.AddField(
            model_name='adopter',
            name='adopted_dogs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adopters', to='app.dog'),
        ),
    ]
