# Generated by Django 5.1.1 on 2024-11-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_adopter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
